### ISSUE TITLE
feat: Validate duplicate channel names [⭐1xp]

### ISSUE THREAD

**Issue by IndieCoderMM** [IndieCoderMM/convoz-chat#17]
Users should not be allowed to create a new channel with duplicate names.

- [ ] When editing or creating a new channel, check for name conflicts. (related file: [*src/features/Channels/ChannelForm.tsx*](https://github.com/IndieCoderMM/convoz-chat/blob/dev/src/features/Channels/ChannelForm.tsx))
- [ ] Notify users with a `toast` message if *Channel name already exists*
- [ ] Channel names are in the format: `channel-name`

**Comment by tran1109** [comment]
tôi có thể thử giải quyết vấn đề này không?

**Comment by IndieCoderMM** [comment]
Yes, please do. Feel free to reach out if you have any questions.
Happy coding! 🚀

**Comment by IndieCoderMM** [comment]
Let's add @tran1109 to @all-contributors for code.

**Comment by IndieCoderMM** [comment]
@all-contributors please add @tran1109 for code.
